"""The pool registry: one row per competitor, loaded as data.

Issue #20 brief §4. Every number carries the command or run id that
produced it (R005). Generated by the characterisation sweep
(offline/pool/sweep.py, run 2026-09-15, seed 0, 96-turn pre-filter +
719-turn classification table); regenerate by re-running the sweep.

Class semantics (behavioural, measured - never read off the source):
- P  open-loop playbook: identical action sequence across seats/seeds
- S  self-reactive: reads its own farm, ignores the opponent
- R  reactive: responds to what we do - the only valid ship-gate class

Baseline numbers: `chista-m1` (the M1 greedy spine) vs the slug in one
719-turn episode, seed 0, weedSpawnChance 0.005, per-seat rewards.
"""

from __future__ import annotations

# {slug: {"class": str, "baseline_vs_m1": {"us", "them", "margin"}}}
REGISTRY: dict[str, dict] = {
    "25-27-strict-future-v27-midgame-meta-reset": {"class": "S", "baseline_us": 2840, "baseline_them": 134606, "baseline_margin": -131766},
    "44-46-strict-future-top-30-v22-price-impact": {"class": "R", "baseline_us": 2840, "baseline_them": 180530, "baseline_margin": -177690},
    "adaptive-public-state-multi-route": {"class": "R", "baseline_us": 2840, "baseline_them": 180210, "baseline_margin": -177370},
    "adaptive-replay-agent": {"class": "R", "baseline_us": 2840, "baseline_them": 177438, "baseline_margin": -174598},
    "adaptive-shop-guard": {"class": "P", "baseline_us": 2840, "baseline_them": 135434, "baseline_margin": -132594},
    "economics-driven-rule-agent-ecobot-v6": {"class": "R", "baseline_us": 2840, "baseline_them": 154784, "baseline_margin": -151944},
    "farming-score-a-mathematical-approach": {"class": "P", "baseline_us": 2840, "baseline_them": 135434, "baseline_margin": -132594},
    "farming-score-v3-replay-revised": {"class": "P", "baseline_us": 2840, "baseline_them": 135434, "baseline_margin": -132594},
    "findings-from-zero-to-top-meta": {"class": "R", "baseline_us": 2840, "baseline_them": 176813, "baseline_margin": -173973},
    "frontier-the-soil-remembers-rain": {"class": "R", "baseline_us": 2840, "baseline_them": 146075, "baseline_margin": -143235},
    "precomputed-schedule-policy": {"class": "P", "baseline_us": 2840, "baseline_them": 179549, "baseline_margin": -176709},
    "v111-8c4s-economic-core-premium-lead": {"class": "S", "baseline_us": 2840, "baseline_them": 154635, "baseline_margin": -151795},
    "v13-r3-top-meta-order-safe-premium-control": {"class": "R", "baseline_us": 2840, "baseline_them": 177438, "baseline_margin": -174598},
    "v16-rc5-high-score-8c-4s-premium-market-lead": {"class": "S", "baseline_us": 2840, "baseline_them": 154635, "baseline_margin": -151795},
    "v16-rc5-r5a-high-score-8c-4s-recovery": {"class": "S", "baseline_us": 2840, "baseline_them": 154635, "baseline_margin": -151795},
    "v20-adaptive-r1-multi-route-agent": {"class": "R", "baseline_us": 2840, "baseline_them": 180272, "baseline_margin": -177432},
    "v21-r1-public-state-route-portfolio": {"class": "R", "baseline_us": 2840, "baseline_them": 180384, "baseline_margin": -177544},
    "v3-agent": {"class": "R", "baseline_us": 2840, "baseline_them": 180530, "baseline_margin": -177690},
    "x544-nah-i-d-win": {"class": "R", "baseline_us": 2840, "baseline_them": 166783, "baseline_margin": -163943},
}


# Three published notebooks shipped byte-identical payloads (SHA-256
# measured 2026-09-15): the pool is 16 distinct agents in 19 slugs.
# alias -> canonical slug; the canonical is the amendment's listing.
DUPLICATE_OF: dict[str, str] = {
    "44-46-strict-future-top-30-v22-price-impact": "v3-agent",
    "farming-score-v3-replay-revised": "farming-score-a-mathematical-approach",
    "v16-rc5-high-score-8c-4s-premium-market-lead": "v111-8c4s-economic-core-premium-lead",
}


def canonical(slug: str) -> str:
    """The canonical slug for an alias (identity for non-duplicates)."""
    return DUPLICATE_OF.get(slug, slug)


def canonical_slugs() -> list[str]:
    """The 16 distinct slugs (aliases excluded)."""
    return [s for s in sorted(REGISTRY) if s not in DUPLICATE_OF]


def get(slug: str) -> dict:
    """One registry row (KeyError for an unknown slug - loud, R005)."""
    return REGISTRY[slug]


def class_of(slug: str) -> str:
    return REGISTRY[slug]["class"]


def dev_and_heldout() -> tuple[list[str], list[str]]:
    """The 14 dev / 5 held-out split, stratified (brief §4).

    Held-out five: all class R (holding back a playbook withholds
    nothing), chosen to span behaviour - includes the one price-aware
    agent (ecobot-v6) per the pool-analysis note.
    """
    heldout = ["economics-driven-rule-agent-ecobot-v6",   # price-aware
               "v13-r3-top-meta-order-safe-premium-control",
               "findings-from-zero-to-top-meta",
               "frontier-the-soil-remembers-rain",
               "v20-adaptive-r1-multi-route-agent"]
    dev = [s for s in sorted(REGISTRY) if s not in heldout]
    assert len(dev) == 14 and len(heldout) == 5
    assert all(REGISTRY[s]["class"].startswith("R") for s in heldout), (
        "held-out five must all be class R (brief section 4)")
    return dev, heldout
